### ISSUE TITLE
Pricing should be updated

### ISSUE THREAD

**Issue by se-bastiaan** [thaliawww/eetFestijn#2]
The Fest has changed prices, we should get hold of a flyer.

**Comment by joren485** [comment]
![flyer_front](https://user-images.githubusercontent.com/7031489/41622596-5f705710-7410-11e8-80a3-02820afc67a7.jpg)
![flyer_back](https://user-images.githubusercontent.com/7031489/41622602-66ec53fe-7410-11e8-82d9-02394f46f42c.jpg)
